### ISSUE TITLE
Enhancement: Support for IDs starting with numbers or consisting of only numbers

### ISSUE THREAD

**Issue by Wilson820** [josias-r/boarding.js#20]
Some of the IDs I use start with numbers, and it is common to use IDs that are generated at runtime with numbers or alphanumeric characters. For some unknown reason, querySelector doesn't support this structure. I am attaching an image of the error generated using the compiled version from the master branch on May 17, 2023.

![image](https://github.com/josias-r/boarding.js/assets/47300720/f39c6472-a2ef-4411-a55b-ae0cfc6623cc)

**Comment by josias-r** [comment]
@Wilson820 Boarding JS also supports an element as an input as an alternative to selectors. So there are the following ways to approach this:

1. Select the element yourself and pass it to boarding.js
2. [Escape the numeric characters for the selector](https://stackoverflow.com/a/20306237/9191773) (`"#\\2428DIV"`)
3. [Use an attribute selector string](https://stackoverflow.com/a/20306218/9191773) (`"[id='2428DIV']"`)
4. Prefix the IDs when you set them `id="element-2428DIV"`

While it is valid in HTML5, it is a limitation by CSS, so it is not up for `boarding.js` to work around it :)
