### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive. See

### ISSUE THREAD

**Issue by zzy-life** [josias-r/boarding.js#21]
![image](https://github.com/josias-r/boarding.js/assets/68179477/a2a07acc-75a8-48af-a572-050fa87fb29d)
![image](https://github.com/josias-r/boarding.js/assets/68179477/6fc7c5a4-efe7-4f89-9574-412b107e5f80)

**Comment by zzy-life** [comment]
I want to use bottom-right but it seems that there is no such attribute

**Comment by josias-r** [comment]
> I want to use bottom-right but it seems that there is no such attribute

From the docs:

```
    // prefferedPosition can be top, bottom, left, right
    prefferedPosition: 'left',
    // alignment can be start, center, end
    alignment: "start"
```

So in your case it would be:
```
{
   "prefferedPosition": "bottom",
   "alignment": "end"
}
```

**Comment by josias-r** [comment]
For the error, could you share a minimal reproduction sandbox?

**Comment by zzy-life** [comment]
It only appears in Google Chrome F12 using the mobile terminal emulator, I think it should not affect
![image](https://github.com/josias-r/boarding.js/assets/68179477/dfa52c8c-4505-4bac-b705-a3a29f85ce1c)
