### ISSUE TITLE
Edit the svg to change the values of the highlighted element

### ISSUE THREAD

**Issue by Dazava** [josias-r/boarding.js#22]
Good morning, how could you edit the lighting of the svg strokes or when you do, do not re-edit and return to its original values if I scroll or remove the scroll. I am calculating some width and height values once the element has been illuminated to edit it, then I create again the string of the svg path’s d attribute to change it with jquery but then if the scroll changes or if the illuminated element is a select, if I select one of your options it also returns to its original values.

**Comment by josias-r** [comment]
@Dazava What drastic changes do you want to apply to the SVG that this is necessary?

You have control over the basic properties such as the color, and border-radius. You also can use CSS to select the SVG and overwrite any properties you want to overwrite that are supported by CSS.
